### ISSUE TITLE
关于聊天记录的问题

### ISSUE THREAD

**Issue by zh185571483** [Yiyiyimu/QQ_History_Backup#12]
我想恢复的是已删好友的聊天记录 
在手机上能看继续浏览
但是用exe填对应qq号后并未恢复
File not found. Please report your directory layout.Traceback (most recent call last):
  File "QQ_History.py", line 192, in main
  File "QQ_History.py", line 13, in __init__
  File "QQ_History.py", line 160, in get_key
  File "QQ_History.py", line 174, in unify_path
OSError: File not found. Please report your directory layout.
log显示如上

**Comment by Yiyiyimu** [comment]
你有files/kc这个文件吗，如果没有的话可以试一下1.41版本，https://github.com/Yiyiyimu/QQ_History_Backup/releases/tag/v1.41

**Comment by Yiyiyimu** [comment]
Close due to no response
