### ISSUE TITLE
关于聊天记录中图片的问题（试图说明

### ISSUE THREAD

**Issue by KingBlin** [Yiyiyimu/QQ_History_Backup#13]
我首先遵照简介，将/sdcard/Andoird/data/com.tencent.mobileqq放到QQ_History_Backup-v2.1文件夹中，直接使用GUI导出，然而导出的聊天记录中并没有图片，尝试几次均如此。
于是便下载了源码，运行，结果出错
ModuleNotFoundError("No module named 'google'")Traceback (most recent call last):
  File "C:\Users\XXX\Desktop\QQ_History_Backup-master\QQ_History.py", line 267, in main
    q.output()
  File "C:\Users\XXX\Desktop\QQ_History_Backup-master\QQ_History.py", line 208, in output
    allmsg = self.message()
  File "C:\Users\XXX\Desktop\QQ_History_Backup-master\QQ_History.py", line 164, in message
    msg_final = self.decrypt(msgdata, msg_type)
  File "C:\Users\XXX\Desktop\QQ_History_Backup-master\QQ_History.py", line 108, in decrypt
    return decode_pic(msg)
  File "C:\Users\XXX\Desktop\QQ_History_Backup-master\QQ_History.py", line 36, in decode_pic
    from proto.RichMsg_pb2 import PicRec
  File "C:\Users\XXX\Desktop\QQ_History_Backup-master\proto\RichMsg_pb2.py", line 5, in <module>
    from google.protobuf import descriptor as _descriptor
ModuleNotFoundError: No module named 'google'
百度一番发现是缺少protobuf这个包，pip install protobuf
再次导出，成功

**Comment by Yiyiyimu** [comment]
噢我这个功能haimeiyou测试过，如果方便的话提个PR吧~

**Comment by Yiyiyimu** [comment]
啊对2.1是没有支持图片导出的。。
