### ISSUE TITLE
明明已经把文件夹com.tencent.mobileqq放在对应的GUI.exe 同一文件夹中，但是却说找不到文件

### ISSUE THREAD

**Issue by fqhwas** [Yiyiyimu/QQ_History_Backup#44]
OSError('File not found. Please report your directory layout.')Traceback (most recent call last):
  File "QQ_History.py", line 280, in main
  File "QQ_History.py", line 36, in __init__
  File "QQ_History.py", line 207, in get_key
  File "QQ_History.py", line 222, in unify_path
OSError: File not found. Please report your directory layout.

**Comment by WyvernCoder** [comment]
我也有这个问题。

**Comment by WyvernCoder** [comment]
我忘记看操作视频了，问题已经解决。

**Comment by brokenplayer5** [comment]
哪里有视频

**Comment by xioahua** [comment]
用手机自带的备份工具备份整个QQ，拷贝备份文件QQ(com.tencent.mobileqq).bak到电脑，用7zip解压找到 com.tencent.mobileqq，注意：这里不能解压backup_qq.zip中的com.tencent.mobileqq。希望作者在使用说明里加一句，否则可能很多人会遇到这个问题。

**Comment by EdwinShadow** [comment]
看下你手机备份的qq是不是已经是qqnt了  好像还不支持qqnt

**Comment by Yiyiyimu** [comment]
@xioahua 方便的话可以提个PR加一句吗，多谢！
