### ISSUE TITLE
导出按操作后提示找不到对应的文件

### ISSUE THREAD

**Issue by 1007283085q** [Yiyiyimu/QQ_History_Backup#51]
OperationalError('no such table: mr_friend_0F960AEF54972609B9E49B9DEEEBDCBC_New')Traceback (most recent call last):
  File "QQ_History.py", line 281, in main
  File "QQ_History.py", line 182, in output
  File "QQ_History.py", line 126, in message
  File "QQ_History.py", line 172, in fill_cursors
sqlite3.OperationalError: no such table: mr_friend_0F960AEF54972609B9E49B9DEEEBDCBC_New

**Comment by supertailcat** [comment]
#44 solved
