### ISSUE TITLE
请问这个是啥问题

### ISSUE THREAD

**Issue by ThenJade** [Yiyiyimu/QQ_History_Backup#52]
OSError('File not found. Please report your directory layout.')Traceback (most recent call last):
  File "QQ_History.py", line 280, in main
  File "QQ_History.py", line 36, in __init__
  File "QQ_History.py", line 207, in get_key
  File "QQ_History.py", line 222, in unify_path
OSError: File not found. Please report your directory layout.

**Comment by YangSJ1** [comment]
同问
